spring:
  application:
    name: movieRecsBot
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:llama3.1:8b-instruct-q4_0}
          temperature: 0.2
          top-p: 0.9

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    webhook-path: ${TELEGRAM_BOT_WEBHOOK_PATH:/tg/webhook}
    webhook-url: ${TELEGRAM_WEBHOOK_URL:}

logging:
  level:
    root: INFO
    com.gnemirko.movieRecsBot: DEBUG
